language: node_js
node_js:
- 13.11.0
env:
  matrix:
  - HOST_URL=https://hellogitlab.com
  global:
  - secure: dV1621QsD2kdsHeY8u5EdPgaaHChVabPbK3nsIW7katHhdcl35gsas1dg/Pyx1ZyDepk0ftdU/ElbYJRFMvgGEF+iJVnDIPG/+Pd9JsSOKSUe1qxw4SzDX9gmgoesHDWGdSCrfF0aIIWbe/IKGMpXq4CKNJPv+fXMPIjh5XDH1nSq+CNlhPhb1CMFe90Bp/ulz3QHP4DPYgk7HNyyEuVhnEgIeXUt70Qk/zRNuj4PHdME9l1rAPr6F/5G5kvV/F+6syn1F9F4SA0GnMaE6E3kxxa51Qt+bfHCigrCYmnr6XIehE4w6EprSy6XhUqj00dfPufH2UqCcLLLvLFcA8pDoAMcISu2nR3iTB/0hKW7NNaV0P8ZebWg5COUvWWx84PsBzZfxIL7nVrk0avN5KIdtapK2h5zAfHTUgyrG/D50NmplXvfcvCE29qW4HkXLg05N372YMMpRIb5Me+POoJeY2Z8gf09CZySJbj8B1LvzQF7wcOxgQxSlsS/xYo+TMbJzshuc37O40bqdZ4mMGYzUqMysvJssg9W3Wtwhf+DLNqU7Q4VIwLz86s59jGYWzBLctQbYAeCxdKSUFKAIOF3taeplnju7G2k562NRwxmIiAXExeBvBvFQlnCfolrOBIB3foktTr8SUAzoB4Wuix4nmjo4SZ2izLQMZujPmgX7E=  # DEPLOY_DOMAIN
  - secure: KTfqE9f5MbWF0bwO9xMDyqsTzWblZKVTxPBFpV4oHBCyobXwYJr4lTbXGBheeaVejiN/ModCwh44tqfLG6KJBdyNgYN827iUKC6UHUKPIxHRWDha83WcVrZ0QTp0e9d1wPILAkzpx4kK8rw0xLHYMMFr2Y9pb/EcmGirRxutR4nKvlNyIlnvibyzodbQQ+SsHzrZrgQZTDSGZAqLDpxCp481iTJUOstZPTG2Sqvslg0PESNRxG3UTAPlp/WXkyuNQAf2Sej0e170TvqnSv425MQC3lluv7ZUI/TrPir2rF6CMW/4j/AQbOTRnJFzTqzad18VcLSo6ePram9XsZCVRW6t5NrC+9Rbg8XFuJJvZzzZm/bPdn5rWbNHUzKRUjsWV6WLzw2r0h5AXH9bzzpglN7zy1qM9/cYmiIV1L9HPJwVTikfQvHVdRlZY5xIz1wMhDcLs4IsJKcazZ8imxXD5YOfSi0uvWEptU+D6XKWtTks5+JWwAL331suY3rny9h0gZeMnaxJSpd2if7Wz+wcjJTBoaUyuT/+JhB6XWNcbRhMXmAQ7c+Sk8OLMf9ZseU9pmWADz80Pqi9zvH/emBSunYc09JU74rL708xPZkRhBwtWnedPzgmZJbEICBnowspYp2HFGYrTDyuk1bsXdCFw/VgZxQpeBgi0rg110HMLHQ=  # DEPLOY_PORT
  - secure: h6bv5C+SV4p1x3eU8mbOKvsbDTezG+/umH3A3wi3YofRwRitPgAM1AUn/YoT1m221/6oSCc1FPhviwQt0JtueqIWqizdDpkJ6570Gauutk/u0cglc6YcmKBIkdW0dvrSPaE4FIGY8vx5GiTup9Ravos8OMxK90prFEyGXqDFfjm3le6S0gcbr4cB+/lLb9sOXLw504o+hbaIHqmCMpYUouwvNSBA+WPkU7VhaXGvTb1fFaIAWhpHJN583qqqW7v7Pzu82hciLYSvG/f3TUH/9KCdnMEohxO9qzs7QNeGEBmi4Sf1EhsiGEYlwxd72qhxW3iMvg3GORdkzmTHiycJ+g2eOGgrRm9WoKqFRHw0YlrWVDewmAoOKXV8eyuyQjny0fwpy3ch4FlrJdE3VCHQbO68WglReU86KEHhOK0e8kGmF4FWt0ZmDvoVf0YBr/Pfr7D9kMjHNaOZVwkVgTSMKNlVhvxD7Hxp4jCqUzR+E+/VUDe9Lu8mdn1yZRm2P77ajAtnzDbVap4PqL/IEaLw0d9t5aUwD9hY28JiY6gjTeiqmr6Tt91jhvxN+eSgguhlGTML+QsWkvwQiA4LdvL1Yp/TYuMjcCFsVRaWArLyZU7bDBayei6v4V910BBmPW933fE9k5oDPdOvALO8Zc3V7PshFtkCFmmFf/maQFCVhhY=  # DEPLOY_USER
  - secure: b3pztkkTOWgilPIg2T0jC/TgX099qeJLfj7QCo5ujLqAclKbIlWIz0xGiDxk2IhcKlS7J+klNhaiLd/P+Wb67W7XUNJBictgvgPGGMoCDsH87tZExi3npMynNl00VNWTasixIHs63RnKGaNCORdJr1YsbF82iR/slRIDy0eaGIxBO1Ttg80FTkDOIrC9swTcQ6xXP26y9jaE1MlZeFiNm2i/QImUIM230pNYdn3OYDaXIcEnDd0quZW36XEJlEQxOgfWgViC3rc4QtW5hvdnI25yJ3RGBFG74ACSy7OQBExvqm1ycVutBbQFuM3EU9DtEb2X8TSZcjAe+nmDonCtP7zcttStaTEvZVmKh2v7xyy+aDxVzAzrBn0EZi/AjACXtkihKOQ0FAMI7UDFUuofMBhl5i0onS2rMIXkDDBzlSyh6gL7flTwDnBojqKhFamxE/g5RREINtWZNVwHPu4kkdfMK/7599cuOAOUP7ckffxcveKGFUD1l+wOOpPlUoj5qz6JxVUnNrNBNxaNgpNIxvrTDdJizgAT9eP8tojjPudy9lt72ABhuUyEV+GOwEwRT0CG9IF+KHBmNCvoFqrHls5A0mjId6mKuQB0rmfGKQ9UQSt3dUgXgQ9F5/kziosOsNkj+jRWJarXoK25uJ/uvjQtEjNc9EgdnH2ck2nOrnU=  # DEPLU_PASSWORD
install:
- echo "Install sshpass"
- sudo apt-get update -y && sudo apt-get install sshpass -y && sshpass -h && sshpass -V 
- echo "Install vuepress"
- yarn global add vuepress
- echo "Install vuepress plugin"
notifications:
  email:
    recipients:
    - mzh@hellogitlab.com
    on_success: always
    on_failure: always
script:
- echo "${TRAVIS_OS_NAME}"
- uname -a
- echo "Check Node.js version" && node -v
- echo "Check yarn version" && yarn -v
- cd myblog && pwd
- yarn install
- yarn add vuepress-plugin-comment -D
- yarn add vuepress-plugin-auto-sidebar -D
- echo "change file contents"
- cp config/secureinfo.js.txt config/secureinfo.js
- sed -i "s/your leancloud appid/${LEAN_APPID}/g" config/secureinfo.js
- sed -i "s/your leancloud appkey/${LEAN_APPKEY}/g" config/secureinfo.js
- yarn docs:build
- echo "Hello Travis"
after_success:
- sshpass -p "${DEPLOY_PASSWORD}" ssh "${DEPLOY_USERNAME}@${DEPLOY_DOMAIN}" -p "${DEPLOY_PORT}"
  'echo "travis" > ~/test.travis'
